# 3.3 重构代码-自定义验证对象

我们之前写的代码，有一些细节问题。

### 1.传入错误的参数，虽然没有添加到数据库，但是返回 结果显示正常

这是因为，form.validate()如果校验不通过，他不会抛出异常，而是会将异常信息存储在form对象中。
所以这个时候我们应该判断如果校验不通过，就抛出一个自定义的异常。


werkzeug为我们提供的大量的异常，都继承自HTTPException，但是这些异常都很具体，不能为我们所用。不过我们可以自己定义一个异常来继承HTTPException


### 2.自定义异常

#### rest中状态码代表的意义
- 400 参数错误
- 401 未授权
- 403 禁止访问
- 404 没有找到资源或者页面
- 500 服务器未知错误
- 200 查询成功
- 201 更新/创建成功
- 204 删除成功
- 301/302 重定向

```python
class ClientTypeError(HTTPException):
    code = 400

    description = (
        'client is invalid'
    )
```

修改后的试图函数
```python
@api.route('/register', methods=['POST'])
def create_client():
    data = request.json
    form = ClientForm(data=data)

    if form.validate():
        promise = {
            ClientTypeEnum.USER_EMAIL: __register_user_by_email
        }
        promise[form.type.data]()
    else:
        raise ClientTypeError()
    return 'success'
```

修改完成之后，已经修复了之前的缺陷，但是这样爆出了两个问题：
1.代码太啰嗦了，每个试图函数里，都需要这么写
2.ClientTypeError只是代表客户端类型异常，其他的参数校验不通过也抛出这个异常的话不合适


### 3.异常返回的标准与重要性
我们的restapi返回的信息主要分为以下三类:
1.页数数据信息
2.操作成功提示信息
3.错误异常信息

如果错误异常信息不够标准，那么客户端很难去处理我们的错误异常